export const restaurantsStats = [
    {
      id:1,
      name: "Wok N Rock",
      owner: "Nawaz Qatri",
      phone: "2252948583",
      status: "active",
      logo: "",
    },
    {
      id:2,
      name: "Papa Jee store",
      owner: "Nawaz",
      phone: "2252948583",
      status: "active",
      logo: "",
    },
    {
      id:3,
      name: "Lovely Roses",
      owner: "Nawaz",
      phone: "2252948583",
      status: "active",
      logo: "",
    },
    {
      id:4,
      name: "Rock Chipsy",
      owner: "Nawaz",
      phone: "2252948583",
      status: "active",
      logo: "",
    },
    {
      id:5,
      name: "Royal Pharmacy Express",
      owner: "Nawaz",
      phone: "2252948583",
      status: "active",
      logo: "",
    },
    {
      id:6,
      name: "McDonald's",
      owner: "Nawaz",
      phone: "2252948583",
      status: "active",
      logo: "",
    },
  ];
